version: '3.2'

services:
  db:
    image: mysql:8.3.0
    container_name: $DB_CONTAINER_NAME
    restart: always
    ports:
      - "${DB_EXPOSE_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: DB_PASSWORD
    volumes:
      - ./docker/db/data:/var/lib/mysql/

  php:
    build: ./docker/php
    container_name: $PHP_CONTAINER_NAME
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./.env:/var/www/.env:ro
      - ./docker/php:/usr/local/etc/php
    depends_on:
      - db

  nginx:
#    build: ./docker/nginx/
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "${NGINX_EXPOSE_PORT}:${NGINX_PORT}"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/logs:/var/log/nginx
      - ./app:/var/www/html
    depends_on:
      - php

